# The URL the site will be built for
#base_url = "https://blog.lingualearn.com"
base_url = "https://tiller1010.github.io/language_learning_blog"
theme = "kita"

title = "LinguaLearn Blog"
description = "Get the latest language learning news."

author = "Tyler Trout"

taxonomies = [{ name = "tags", rss = true, paginate_by = 5 }]

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here

