# The URL the site will be built for
base_url = "https://blog.lingualearn.net"
#base_url = "https://tiller1010.github.io/language_learning_blog"
theme = "kita"

title = "LinguaLearn Blog"
description = "Get the latest language learning news."

author = "Tyler Trout"

taxonomies = [{ name = "tags", rss = true, paginate_by = 5 }]

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here

[[extra.menu]]
name = "About"
url = "$BASE_URL/about"

[[extra.menu]]
name = "Main Site"
url = "https://www.lingualearn.net"

[extra.profile]
name = "Blog - LinguaLearn"
bio = "LinguaLearn is a website where you can practice your language skills with other learners around the world. Read about language learning topics here."

[[extra.profile.social]]
name = "github"
url = "https://github.com/tiller1010"

[[extra.profile.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/tyler-j-trout/"
